<a href="https://colab.research.google.com/github/NajlaaNawaii/Math-and-Machine-Learning-Puzzles/blob/main/ML%20Code%20Challenges/ML_Code_Challenges_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ML CHALLENGES LINK: https://www.deep-ml.com/?difficulty=&category=linear+algebra&solved=&page=1

#Linear Algebra Easy! ( 15 problems )

##Matrix times Vector (easy) ✔
Write a Python function that takes the dot product of a matrix and a vector. return -1 if the matrix could not be dotted with the vector

In [ ]:
a=[[1,2],[3,4]]
b=[5,6]

In [ ]:
def matrix_dot_vector(a:list[list[int|float]],b:list[int|float])-> list[int|float]:
  if len(a[0]) != len(b):
	  return -1

  c=[0]*len(a)
  for i in range(len(a)):
    for j in range(len(a[i])):
      c[i]+=a[i][j]*b[j]
  return c

matrix_dot_vector(a,b)

[17, 39]

In [ ]:
#Using List comprehension
def matrix_dot_vector(a: list[list[int | float]], b: list[int | float]) -> list[int | float]:
    if len(a[0]) != len(b):
        return -1
    return [sum(a_row[col] * b[col] for col in range(len(a_row))) for a_row in a]

matrix_dot_vector(a,b)

[17, 39]

In [ ]:
def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
	k=[]
	if len (a[0])==len(b):
		for row in a:
			element=0
			for i in range(len(row)):
				element+=row[i]*b[i]
			k.append(element)
		return k

	else:
		return -1

In [ ]:
matrix_dot_vector(a,b)

[17, 39]

##Transpose of a Matrix (easy) ✔
Write a Python function that computes the transpose of a given matrix.

In [ ]:
a=[[1,2],[3,4],[5,6]]


In [ ]:
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
	b=[[0 for row in range(len(a))] for col in range(len(a[0]))]
	for i in range(len(a[0])):
		for j in range(len(a)):
			b[i][j]=a[j][i]
	return b

transpose_matrix(a)

[[1, 3, 5], [2, 4, 6]]

In [ ]:
#Using zip, it first unpack into tuples, returns a tuple of similar indices
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
  #takes each inner list as a seperate argument for zip; unpacks
  return [ list(row) for row in zip(*a)]

transpose_matrix(a)

[[1, 3, 5], [2, 4, 6]]

In [ ]:
import numpy as np
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
    b=np.empty((len(a[0]),len(a)),dtype=int)
    for i in range(len(a)):
        for j in range(len(a[0])):
            b[j][i]=a[i][j]
    return b.tolist()


transpose_matrix(a)

[[1, 3, 5], [2, 4, 6]]

In [ ]:
import numpy as np
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
    a=np.array(a)
    b=a.T
    return b.tolist()


transpose_matrix(a)

[[1, 3, 5], [2, 4, 6]]

##Transformation Matrix from Basis B to C (easy) ✔
Given basis vectors in two different bases B and C for R^3, write a Python function to compute the transformation matrix P from basis B to C.


 #### To Change Basis:

1. **Compute the Transformation Matrix**:

   $$
   P = C^{-1} \times B
   $$

2. **Find the New Coordinates**:

   $$
   [\mathbf{v}]_C = P \times [\mathbf{v}]_B
   $$


In [ ]:
B = [[1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]]
C = [[1, 2.3, 3],
    [4.4, 25, 6],
    [7.4, 8, 9]]


In [ ]:
import numpy as np
def transform_basis(B: list[list[int]], C: list[list[int]]) -> list[list[float]]:

  #it's only for creating list so don't forget [],Doing it the hard way!
  C=np.array(C)
  C_inversed=np.linalg.inv(C)

  P_transposed = [[sum(c_row[col] * b_col[col] for col in range(len(c_row))) for c_row in C_inversed] for b_col in [list(row) for row in zip(*B)]]
  P=[list(row) for row in zip(*P_transposed)] #because the basis are the cols
  return np.round(P,4)

transform_basis(B,C)


array([[-0.6772, -0.0126,  0.2342],
       [-0.0184,  0.0505, -0.0275],
       [ 0.5732, -0.0345, -0.0569]])

In [ ]:
import numpy as np
def transform_basis(B: list[list[int]], C: list[list[int]]) -> list[list[float]]:
  inverse_dest_basis=np.linalg.inv(C)
  P=inverse_dest_basis.dot(B)

  return np.round(P,4)


transform_basis(B,C)

array([[-0.6772, -0.0126,  0.2342],
       [-0.0184,  0.0505, -0.0275],
       [ 0.5732, -0.0345, -0.0569]])

##Reshape Matrix (easy) ✔
Write a Python function that reshapes a given matrix into a specified shape.

In [ ]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
	#Write your code here and return a python list after reshaping by using numpy's tolist() method
	#Find a way o assert it can be reshaped
  numbers_count=sum(len(row) for row in a)
  required_count=new_shape[0]*new_shape[1]
  if numbers_count!=required_count:
    return "It can't be reshaped"
  reshaped_matrix= np.array(a).reshape(new_shape).tolist()
  return reshaped_matrix

In [ ]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
	#Write your code here and return a python list after reshaping by using numpy's tolist() method
    a=np.array(a)
    if a.size == np.prod(new_shape) :
        reshaped_matrix=np.reshape(a,new_shape).tolist()
        return reshaped_matrix

    else:
        return []


In [ ]:
#test reshape matrix
a=[[1,2],[3,4],[5,6]]
new_shape=(2,3)
reshape_matrix(a,new_shape)
#test when can't be reshaped
# new_shape=(3,3)
# reshape_matrix(a,new_shape)

[[1, 2, 3], [4, 5, 6]]

##Convert Vector to Diagonal Matrix(easy) ✔
Write a Python function to convert a 1D numpy array into a diagonal matrix. The function should take in a 1D numpy array x and return a 2D numpy array representing the diagonal matrix.

In [ ]:
x = np.array([1, 2, 3])

In [ ]:
import numpy as np
#Using for loop and zeros matrix
def make_diagonal(x):
	# Your code here
	length=len(x)
	output=np.zeros((length,length))
	for i in range(length):
		output[i][i]=x[i]
	return output

make_diagonal(x)

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [ ]:
def make_diagonal(x):
  Identity=np.identity(len(x))
  #Broadcasting; x is (1,n), then it's duplicated as (n,n) to do element-wise multiplication
  #No Loops!
  output=Identity*x #element wise multiplication
  return output
make_diagonal(x)

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [ ]:
import numpy as np

def make_diagonal(x):
	# Your code here
    X=np.diag(x)
    return X
make_diagonal(x)

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

##Calculate Mean by Row or Column (easy) ✔
Write a Python function that calculates the mean of a matrix either by row or by column, based on a given mode. The function should take a matrix (list of lists) and a mode ('row' or 'column') as input and return a list of means according to the specified mode.

In [ ]:
def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:
	if mode == 'column':
		return [sum(col)/len(col) for col in zip(*matrix)]
	elif mode == "row":
		return [sum(row)/len(row) for row in matrix]
	else:
		return "You didn't specify a mode: row,column"

#test calculate_matrix_mean
matrix=[[1,2,3],[4,5,6]]
mode="row"
calculate_matrix_mean(matrix,mode)

[2.0, 5.0]

In [ ]:
#Naming the axis of summing
mean_across_rows = np.mean(matrix, axis=0)
print("Mean across rows (for each column):", mean_across_rows)

mean_across_cols = np.mean(matrix, axis=1)
print("Mean across columns (for each row):", mean_across_cols)

Mean across rows (for each column): [2.5 3.5 4.5]
Mean across columns (for each row): [2. 5.]


In [ ]:
import numpy as np
def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:
    if mode == "row":
        means=np.mean(matrix,axis=1)
    else:
        means=np.mean(matrix,axis=0)
    return means

calculate_matrix_mean(matrix,mode)

array([2., 5.])

##Scalar Multiplication of a Matrix (easy) ✔
Write a Python function that multiplies a matrix by a scalar and returns the result.

In [ ]:
#Using list comprehension
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
	return [[element * scalar for element in row] for row in matrix]

#Test scalar_multiply
matrix=[[1,2,3],[4,5,6]]
scalar=2
scalar_multiply(matrix,scalar)

[[2, 4, 6], [8, 10, 12]]

In [ ]:
#Using numpy and broadcasting
import numpy as np
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
	# matrix*scalar==> duplicates, to perform has to be numpy
	return (np.array(matrix)*scalar).tolist()




#test scalar_multiply
matrix=[[1,2,3],[4,5,6]]
scalar=2
scalar_multiply(matrix,scalar)


[[2, 4, 6], [8, 10, 12]]

In [ ]:
import numpy as np
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
    matrix=np.array(matrix)
    result=scalar*matrix
    return result.tolist()


scalar_multiply(matrix,scalar)


[[2, 4, 6], [8, 10, 12]]

##Implement Compressed Row Sparse Matrix (CSR) Format Conversion (easy) ✔
Write a function compressed_row_sparse_matrix(dense_matrix) that takes a 2D list dense_matrix as input and returns a tuple containing three lists:

Values array: List of all non-zero elements in row-major order.
Column indices array: Column index for each non-zero element in the values array.
Row pointer array: Cumulative number of non-zero elements per row, to indicate the start of each row in the values array.

In [4]:
def compressed_row_sparse_matrix(dense_matrix):
	"""
	Convert a dense matrix to its Compressed Row Sparse (CSR) representation.

	:param dense_matrix: 2D list representing a dense matrix
	:return: A tuple containing (values array, column indices array, row pointer array)
	"""
	vals=[]
	col_idx=[]
	row_ptr=[0]
	for row in dense_matrix:
		for i,val in enumerate(row):
			if val != 0:
				vals.append(val)
				col_idx.append(i)

		row_ptr.append(len(vals))

	return vals, col_idx,row_ptr



In [10]:
dense_matrix = [
    [1, 0, 0, 0],
    [0, 2, 0, 0],
    [3, 0, 4, 0],
    [1, 0, 0, 5]
]
compressed_row_sparse_matrix(dense_matrix)

([1, 2, 3, 4, 1, 5], [0, 1, 0, 2, 0, 3], [0, 1, 2, 4, 6])

In [6]:
#Using Scipy
from scipy.sparse import csr_matrix
csr = csr_matrix(dense_matrix)
print("Values array:", csr.data)
print("Column indices array:", csr.indices)
print("Row pointer array:", csr.indptr)

Values array: [1 2 3 4 1 5]
Column indices array: [0 1 0 2 0 3]
Row pointer array: [0 1 2 4 6]


##Implement Compressed Column Sparse Matrix Format (CSC) (easy) ✔
Your task is to implement a function that converts a dense matrix into its Compressed Column Sparse (CSC) representation. The CSC format stores only non-zero elements of the matrix and is efficient for matrices with a high number of zero elements.

Write a function compressed_col_sparse_matrix(dense_matrix) that takes in a two-dimensional list dense_matrix and returns a tuple of three lists:

values: List of non-zero elements, stored in column-major order.
row indices: List of row indices corresponding to each value in the values array.
column pointer: List that indicates the starting index of each column in the values array.



In [24]:
def compressed_col_sparse_matrix(dense_matrix):

	"""
	Convert a dense matrix into its Compressed Column Sparse (CSC) representation.

	:param dense_matrix: List of lists representing the dense matrix
	:return: Tuple of (values, row indices, column pointer)
	"""

	vals=[]
	row_idx=[]
	col_ptr=[0]
	for row in zip(*dense_matrix):
		for i,val in enumerate(row):
			if val != 0:
				vals.append(val)
				row_idx.append(i)

		col_ptr.append(len(vals))

	return vals, row_idx,col_ptr



In [26]:
dense_matrix = [
    [1, 0, 0, 0],
    [0, 2, 0, 0],
    [3, 0, 4, 0],
    [1, 0, 0, 5]
]
compressed_col_sparse_matrix(dense_matrix)

([1, 3, 1, 2, 4, 5], [0, 2, 3, 1, 2, 3], [0, 3, 4, 5, 6])

In [28]:
#Using Scipy
from scipy.sparse import csc_matrix
csc = csc_matrix(dense_matrix)
print("Values array:", csc.data)
print("Column indices array:", csc.indices)
print("Row pointer array:", csc.indptr)

Values array: [1 3 1 2 4 5]
Column indices array: [0 2 3 1 2 3]
Row pointer array: [0 3 4 5 6]


##Implement Orthogonal Projection of a Vector onto a Line (easy) ✔
Write a function orthogonal_projection(v, L) that takes in two lists, v (the vector to be projected) and L (the line vector), and returns the orthogonal projection of v onto L. The function should output a list representing the projection vector rounded to three decimal places.



In [32]:
import numpy as np
def orthogonal_projection(v, L):
	"""
	Compute the orthogonal projection of vector v onto line L.

	:param v: The vector to be projected
	:param L: The line vector defining the direction of projection
	:return: List representing the projection of v onto L
	"""
	v=np.array(v,dtype=float)
	L=np.array(L,dtype=float)
	Vector = (np.dot(v, L) / np.dot(L, L)) * L

	return np.round(Vector,3)



v = [3, 4]
L = [1, 0]
orthogonal_projection(v,L)

array([3., 0.])

##Calculate Cosine Similarity Between Vectors (easy) ✔
In this task, you need to implement a function cosine_similarity(v1, v2) that calculates the cosine similarity between two vectors. Cosine similarity measures the cosine of the angle between two vectors, indicating their directional similarity.

Input:
v1 and v2: Numpy arrays representing the input vectors.
Output:
A float representing the cosine similarity, rounded to three decimal places.
Constraints:
Both input vectors must have the same shape.
Input vectors cannot be empty or have zero magnitude.



In [33]:
import numpy as np

def cosine_similarity(v1, v2):
    v1 = np.array(v1, dtype=float)
    v2 = np.array(v2, dtype=float)

    if v1.shape != v2.shape:
        print("Vectors don't have the right shapes!")
        return None

    mag_v1 = np.linalg.norm(v1)
    mag_v2 = np.linalg.norm(v2)

    if mag_v1 == 0 or mag_v2 == 0:
        print("The magnitudes are zero.")
        return None

    similarity = np.dot(v1, v2) / (mag_v1 * mag_v2)
    return np.round(similarity, 3)


In [35]:
v1 = np.array([1, 2, 3])
v2 = np.array([2, 4, 6])

result = cosine_similarity(v1, v2)
print(result)


1.0


##Dot Product Calculator (easy) ✔

Write a Python function to calculate the dot product of two vectors. The function should take two 1D NumPy arrays as input and return the dot product as a single number.

In [7]:
import numpy as np
def calculate_dot_product(vec1, vec2) -> float:
  """
	Calculate the dot product of two vectors.
	Args:
		vec1 (numpy.ndarray): 1D array representing the first vector.
		vec2 (numpy.ndarray): 1D array representing the second vector.
	"""
  result=vec1.dot(vec2)
  return float(result)


In [8]:
vec1 = np.array([1, 2, 3])
vec2 = np.array([4, 5, 6])
calculate_dot_product(vec1, vec2)

32.0

##Phi Transformation for Polynomial Features(easy) ✔

Write a Python function to perform a Phi Transformation that maps input features into a higher-dimensional space by generating polynomial features. The transformation allows models like linear regression to fit nonlinear data by introducing new feature dimensions that represent polynomial combinations of the original input features. The function should take a list of numerical data and a degree as inputs, and return a nested list where each inner list represents the transformed features of a data point. If the degree is less than 0, the function should return an empty list.



In [11]:
import numpy as np
def phi_transform(data: list[float], degree: int) -> list[list[float]]:
  """
  Perform a Phi Transformation to map input features into a higher-dimensional space by generating polynomial features.

  Args:
    data (list[float]): A list of numerical values to transform.
    degree (int): The degree of the polynomial expansion.
  """
  result=[]
  for x in data:
    result.append([x**deg for deg in range(degree+1)])

  return result

In [12]:
data = [1.0, 2.0]
degree = 2
phi_transform(data,degree)

[[1.0, 1.0, 1.0], [1.0, 2.0, 4.0]]

##Vector Element-wise Sum (easy) ✔
Write a Python function that computes the element-wise sum of two vectors. The function should return a new vector representing the resulting sum if the operation is valid, or -1 if the vectors have incompatible dimensions. Two vectors (lists) can be summed element-wise only if they are of the same length.

In [2]:
def vector_sum(a: list[int|float], b: list[int|float]) -> list[int|float]:
	# Return the element-wise sum of vectors 'a' and 'b'.
	# If vectors have different lengths, return -1.
    if len(a) == len(b):
        return [sum(i) for i in zip(a,b)]
    else:
        return -1

vector_sum([1, 2], [3])

-1

##Compute the Cross Product of Two 3D Vectors (easy) ✔
Implement a function to compute the cross product of two 3-dimensional vectors. The cross product of two vectors results in a third vector that is perpendicular to both and follows the right-hand rule. This concept is fundamental in physics, engineering, and 3D graphics.



In [3]:
import numpy as np

def cross_product(a, b):
    # Your code here
    if len(a) == len(b):
         return np.cross(a,b)

#Linear Algebra Medium (13 problems)!

##Calculate Covariance Matrix (medium) ✔
Write a Python function that calculates the covariance matrix from a list of vectors. Assume that the input list represents a dataset where each vector is a feature, and vectors are of equal length.


### Covariance Equations

1. **Covariance using Expected Value (E)**:

   $$
   \text{Cov}(X, Y) = \mathbb{E}[(X - \mathbb{E}[X])(Y - \mathbb{E}[Y])]
   $$

2. **Covariance using Summation**:

   $$
   \text{Cov}(X, Y) = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{n-1}
   $$


In [ ]:
import numpy as np
def calculate_covariance_matrix(vectors: list[list[float]]) -> list[list[float]]:
	length= len(vectors)
	samples_length= len(vectors[0])
	rows_means= [sum(feature)/samples_length for feature in vectors]
	covariance_matrix=np.zeros((length,length))
  #Default axis=0,
	covariance_matrix=[[ ( ( np.sum((np.array(vectors[i])-rows_means[i])*(np.array(vectors[j])-rows_means[j]))  ) /(samples_length-1) ) for j in range(length) ] for i in range(length)]
	return np.round(covariance_matrix,1)

#test calculate_covariance_matrix
vectors = [[1, 2, 3], [4, 5, 6]]
calculate_covariance_matrix(vectors)


array([[1., 1.],
       [1., 1.]])

In [ ]:
import numpy as np
def calculate_covariance_matrix(vectors: list[list[float]]) -> list[list[float]]:
    data = np.array(vectors, dtype=np.float64)
    #unbiased estimator
    covariance_matrix = np.cov(data, bias=False)
    covariance_matrix_rounded = np.round(covariance_matrix, 1)
    return covariance_matrix_rounded.tolist()

#test calculate_covariance_matrix
vectors = [[1, 2, 3], [4, 5, 6]]
calculate_covariance_matrix(vectors)

[[1.0, 1.0], [1.0, 1.0]]

##Matrix Transformation (medium) ✔
Write a Python function that transforms a given matrix A using the operation
$
T^{(−1)}
A
S$
, where T and S are invertible matrices. The function should first validate if the matrices T and S are invertible, and then perform the transformation. In cases where there is no solution return -1



In [24]:
import numpy as np

def transform_matrix(A: list[list[int|float]], T: list[list[int|float]], S: list[list[int|float]]) -> list[list[int|float]]:
    A=np.array(A,dtype=float)
    T=np.array(T,dtype=float)
    S=np.array(S,dtype=float)


    detT=np.isclose(np.linalg.det(T), 0)
    detS=np.isclose(np.linalg.det(S),0)


    if  detT or  detS:
      return -1
    else:
        return (np.linalg.inv(T)) @ A @ S


In [25]:
A = [[1, 0],
     [0, 1]]

T = [[2, 1],
     [0, 1]]        # det = 2  ≠ 0  (invertible)
S = [[1, 3],
     [0, 1]]        # det = 1  ≠ 0  (invertible)

print(transform_matrix(A, T, S))


[[0.5 1. ]
 [0.  1. ]]


##Calculate 2x2 Matrix Inverse (medium) ✔
Write a Python function that calculates the inverse of a 2x2 matrix. Return 'None' if the matrix is not invertible.





In [26]:
import numpy as np
def inverse_2x2(matrix: list[list[float]]) -> list[list[float]]:
    detM=np.linalg.det(matrix)
    if np.isclose(detM,0):
        return None
    inverse=np.linalg.inv(matrix)
    return inverse