<a href="https://colab.research.google.com/github/NajlaaNawaii/Math-and-Machine-Learning-Puzzles/blob/main/ML%20Code%20Challenges/ML_Code_Challenges_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ML CHALLENGES LINK: https://www.deep-ml.com/?difficulty=&category=linear+algebra&solved=&page=1

#Linear Algebra Easy!

##Matrix times Vector (easy) ✔
Write a Python function that takes the dot product of a matrix and a vector. return -1 if the matrix could not be dotted with the vector

In [3]:
a=[[1,2],[3,4]]
b=[5,6]

In [ ]:
def matrix_dot_vector(a:list[list[int|float]],b:list[int|float])-> list[int|float]:
  if len(a[0]) != len(b):
	  return -1

  c=[0]*len(a)
  for i in range(len(a)):
    for j in range(len(a[i])):
      c[i]+=a[i][j]*b[j]
  return c

matrix_dot_vector(a,b)

[17, 39]

In [ ]:
#Using List comprehension
def matrix_dot_vector(a: list[list[int | float]], b: list[int | float]) -> list[int | float]:
    if len(a[0]) != len(b):
        return -1
    return [sum(a_row[col] * b[col] for col in range(len(a_row))) for a_row in a]

matrix_dot_vector(a,b)

[17, 39]

In [1]:
def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
	k=[]
	if len (a[0])==len(b):
		for row in a:
			element=0
			for i in range(len(row)):
				element+=row[i]*b[i]
			k.append(element)
		return k

	else:
		return -1

In [4]:
matrix_dot_vector(a,b)

[17, 39]

##Transpose of a Matrix (easy) ✔
Write a Python function that computes the transpose of a given matrix.

In [5]:
a=[[1,2],[3,4],[5,6]]


In [ ]:
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
	b=[[0 for row in range(len(a))] for col in range(len(a[0]))]
	for i in range(len(a[0])):
		for j in range(len(a)):
			b[i][j]=a[j][i]
	return b

transpose_matrix(a)

[[1, 3, 5], [2, 4, 6]]

In [ ]:
#Using zip, it first unpack into tuples, returns a tuple of similar indices
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
  #takes each inner list as a seperate argument for zip; unpacks
  return [ list(row) for row in zip(*a)]

transpose_matrix(a)

[[1, 3, 5], [2, 4, 6]]

In [12]:
import numpy as np
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
    b=np.empty((len(a[0]),len(a)),dtype=int)
    for i in range(len(a)):
        for j in range(len(a[0])):
            b[j][i]=a[i][j]
    return b.tolist()


transpose_matrix(a)

[[1, 3, 5], [2, 4, 6]]

##Transformation Matrix from Basis B to C (easy) ✔
Given basis vectors in two different bases B and C for R^3, write a Python function to compute the transformation matrix P from basis B to C.


 #### To Change Basis:

1. **Compute the Transformation Matrix**:

   $$
   P = C^{-1} \times B
   $$

2. **Find the New Coordinates**:

   $$
   [\mathbf{v}]_C = P \times [\mathbf{v}]_B
   $$


In [ ]:
B = [[1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]]
C = [[1, 2.3, 3],
    [4.4, 25, 6],
    [7.4, 8, 9]]


In [ ]:
import numpy as np
def transform_basis(B: list[list[int]], C: list[list[int]]) -> list[list[float]]:

  #it's only for creating list so don't forget [],Doing it the hard way!
  C=np.array(C)
  C_inversed=np.linalg.inv(C)

  P_transposed = [[sum(c_row[col] * b_col[col] for col in range(len(c_row))) for c_row in C_inversed] for b_col in [list(row) for row in zip(*B)]]
  P=[list(row) for row in zip(*P_transposed)] #because the basis are the cols
  return np.round(P,4)

transform_basis(B,C)


array([[-0.6772, -0.0126,  0.2342],
       [-0.0184,  0.0505, -0.0275],
       [ 0.5732, -0.0345, -0.0569]])

In [ ]:
import numpy as np
def transform_basis(B: list[list[int]], C: list[list[int]]) -> list[list[float]]:

  #it's only for creating list so don't forget [],Doing it the hard way!
  B=np.array(B)
  C=np.array(C)
  C_inversed=np.linalg.inv(C)

  P= C_inversed.dot(B)
  return np.round(P,4)


transform_basis(B,C)

array([[-0.6772, -0.0126,  0.2342],
       [-0.0184,  0.0505, -0.0275],
       [ 0.5732, -0.0345, -0.0569]])

##Reshape Matrix (easy) ✔
Write a Python function that reshapes a given matrix into a specified shape.

In [ ]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
	#Write your code here and return a python list after reshaping by using numpy's tolist() method
	#Find a way o assert it can be reshaped
  numbers_count=sum(len(row) for row in a)
  required_count=new_shape[0]*new_shape[1]
  if numbers_count!=required_count:
    return "It can't be reshaped"
  reshaped_matrix= np.array(a).reshape(new_shape).tolist()
  return reshaped_matrix

In [ ]:
#test reshape matrix
a=[[1,2],[3,4],[5,6]]
new_shape=(2,3)
reshape_matrix(a,new_shape)
#test when can't be reshaped
# new_shape=(3,3)
# reshape_matrix(a,new_shape)

[[1, 2, 3], [4, 5, 6]]

##Convert Vector to Diagonal Matrix(easy) ✔
Write a Python function to convert a 1D numpy array into a diagonal matrix. The function should take in a 1D numpy array x and return a 2D numpy array representing the diagonal matrix.

In [ ]:
x = np.array([1, 2, 3])

In [ ]:
import numpy as np
#Using for loop and zeros matrix
def make_diagonal(x):
	# Your code here
	length=len(x)
	output=np.zeros((length,length))
	for i in range(length):
		output[i][i]=x[i]
	return output

make_diagonal(x)

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [ ]:
def make_diagonal(x):
  Identity=np.identity(len(x))
  #Broadcasting; x is (1,n), then it's duplicated as (n,n) to do element-wise multiplication
  #No Loops!
  output=Identity*x
  return output
make_diagonal(x)

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

##Calculate Mean by Row or Column (easy) ✔
Write a Python function that calculates the mean of a matrix either by row or by column, based on a given mode. The function should take a matrix (list of lists) and a mode ('row' or 'column') as input and return a list of means according to the specified mode.

In [ ]:
def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:
	if mode == 'column':
		return [sum(col)/len(col) for col in zip(*matrix)]
	elif mode == "row":
		return [sum(row)/len(row) for row in matrix]
	else:
		return "You didn't specify a mode: row,column"

#test calculate_matrix_mean
matrix=[[1,2,3],[4,5,6]]
mode="column"
calculate_matrix_mean(matrix,mode)

[2.5, 3.5, 4.5]

In [ ]:
#Naming the axis of summing
mean_across_rows = np.mean(matrix, axis=0)
print("Mean across rows (for each column):", mean_across_rows)

mean_across_cols = np.mean(matrix, axis=1)
print("Mean across columns (for each row):", mean_across_cols)

Mean across rows (for each column): [2.5 3.5 4.5]
Mean across columns (for each row): [2. 5.]


##Scalar Multiplication of a Matrix (easy) ✔
Write a Python function that multiplies a matrix by a scalar and returns the result.

In [ ]:
#Using list comprehension
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
	return [[element * scalar for element in row] for row in matrix]

#Test scalar_multiply
matrix=[[1,2,3],[4,5,6]]
scalar=2
scalar_multiply(matrix,scalar)

[[2, 4, 6], [8, 10, 12]]

In [ ]:
#Using numpy and broadcasting
import numpy as np
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
	# matrix*scalar==> duplicates, to perform has to be numpy
	return (np.array(matrix)*scalar).tolist()




#test scalar_multiply
matrix=[[1,2,3],[4,5,6]]
scalar=2
scalar_multiply(matrix,scalar)


[[2, 4, 6], [8, 10, 12]]

##Implement Compressed Row Sparse Matrix (CSR) Format Conversion (easy) ✔
Write a function compressed_row_sparse_matrix(dense_matrix) that takes a 2D list dense_matrix as input and returns a tuple containing three lists:

Values array: List of all non-zero elements in row-major order.
Column indices array: Column index for each non-zero element in the values array.
Row pointer array: Cumulative number of non-zero elements per row, to indicate the start of each row in the values array.

In [ ]:
def compressed_row_sparse_matrix(dense_matrix):
	"""
	Convert a dense matrix to its Compressed Row Sparse (CSR) representation.

	:param dense_matrix: 2D list representing a dense matrix
	:return: A tuple containing (values array, column indices array, row pointer array)
	"""
	vals=[]
	col_idx=[]
	row_ptr=[0]
	for row in dense_matrix:
		for i,val in enumerate(row):
			if val != 0:
				vals.append(val)
				col_idx.append(i)

		row_ptr.append(len(vals))

	return vals, col_idx,row_ptr



In [ ]:
dense_matrix = [
    [1, 0, 0, 0],
    [0, 2, 0, 0],
    [3, 0, 4, 0],
    [1, 0, 0, 5]
]
compressed_row_sparse_matrix(dense_matrix)

([1, 2, 3, 4, 1, 5], [0, 1, 0, 2, 0, 3], [0, 1, 2, 4, 6])

In [ ]:
#Using Scipy
from scipy.sparse import csr_matrix
csr = csr_matrix(dense_matrix)
print("Values array:", csr.data)
print("Column indices array:", csr.indices)
print("Row pointer array:", csr.indptr)

Values array: [1 2 3 4 1 5]
Column indices array: [0 1 0 2 0 3]
Row pointer array: [0 1 2 4 6]


##Implement Orthogonal Projection of a Vector onto a Line (easy) ✔
Write a function orthogonal_projection(v, L) that takes in two lists, v (the vector to be projected) and L (the line vector), and returns the orthogonal projection of v onto L. The function should output a list representing the projection vector rounded to three decimal places.



In [ ]:
import numpy as np
def orthogonal_projection(v, L):
	"""
	Compute the orthogonal projection of vector v onto line L.

	:param v: The vector to be projected
	:param L: The line vector defining the direction of projection
	:return: List representing the projection of v onto L
	"""
	v=np.array(v)
	L=np.array(L)
	v_L= v.dot(L)
	L_L=L.dot(L)
	return ( v_L / L_L) * L


v = [3, 4]
L = [1, 0]
orthogonal_projection(v,L)

array([3., 0.])

#Linear Algebra Medium (11 problems)!

##Calculate Covariance Matrix (medium) ✔
Write a Python function that calculates the covariance matrix from a list of vectors. Assume that the input list represents a dataset where each vector is a feature, and vectors are of equal length.


### Covariance Equations

1. **Covariance using Expected Value (E)**:

   $$
   \text{Cov}(X, Y) = \mathbb{E}[(X - \mathbb{E}[X])(Y - \mathbb{E}[Y])]
   $$

2. **Covariance using Summation**:

   $$
   \text{Cov}(X, Y) = \frac{\sum_{i=1}^{n}(x_i - \bar{x})(y_i - \bar{y})}{n-1}
   $$


In [ ]:
import numpy as np
def calculate_covariance_matrix(vectors: list[list[float]]) -> list[list[float]]:
	length= len(vectors)
	samples_length= len(vectors[0])
	rows_means= [sum(feature)/samples_length for feature in vectors]
	covariance_matrix=np.zeros((length,length))
  #Default axis=0,
	covariance_matrix=[[ ( ( np.sum((np.array(vectors[i])-rows_means[i])*(np.array(vectors[j])-rows_means[j]))  ) /(samples_length-1) ) for j in range(length) ] for i in range(length)]
	return np.round(covariance_matrix,1)

#test calculate_covariance_matrix
vectors = [[1, 2, 3], [4, 5, 6]]
calculate_covariance_matrix(vectors)


array([[1., 1.],
       [1., 1.]])

In [ ]:
import numpy as np
def calculate_covariance_matrix(vectors: list[list[float]]) -> list[list[float]]:
    data = np.array(vectors, dtype=np.float64)
    #unbiased estimator
    covariance_matrix = np.cov(data, bias=False)
    covariance_matrix_rounded = np.round(covariance_matrix, 1)
    return covariance_matrix_rounded.tolist()

#test calculate_covariance_matrix
vectors = [[1, 2, 3], [4, 5, 6]]
calculate_covariance_matrix(vectors)

[[1.0, 1.0], [1.0, 1.0]]