<a href="https://colab.research.google.com/github/NajlaaNawaii/Math-and-Machine-Learning-Puzzles/blob/main/ML%20Code%20Challenges/ML_Code_Challenges_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#ML CHALLENGES LINK: https://www.deep-ml.com/?difficulty=&category=linear+algebra&solved=&page=1

#Linear Algebra Easy (7 problems)!

##Matrix times Vector (easy) ✔
Write a Python function that takes the dot product of a matrix and a vector. return -1 if the matrix could not be dotted with the vector

In [16]:
a=[[1,2],[3,4]]
b=[5,6]

In [17]:
def matrix_dot_vector(a:list[list[int|float]],b:list[int|float])-> list[int|float]:
  if len(a[0]) != len(b):
	  return -1

  c=[0]*len(a)
  for i in range(len(a)):
    for j in range(len(a[i])):
      c[i]+=a[i][j]*b[j]
  return c

matrix_dot_vector(a,b)

[17, 39]

In [18]:
#Using List comprehension
def matrix_dot_vector(a: list[list[int | float]], b: list[int | float]) -> list[int | float]:
    if len(a[0]) != len(b):
        return -1
    return [sum(a_row[col] * b[col] for col in range(len(a_row))) for a_row in a]

matrix_dot_vector(a,b)

[17, 39]

##Transpose of a Matrix (easy) ✔
Write a Python function that computes the transpose of a given matrix.

In [19]:
a=[[1,2],[3,4],[5,6]]

In [20]:
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
	b=[[0 for row in range(len(a))] for col in range(len(a[0]))]
	for i in range(len(a[0])):
		for j in range(len(a)):
			b[i][j]=a[j][i]
	return b

transpose_matrix(a)

[[1, 3, 5], [2, 4, 6]]

In [21]:
#Using zip, it first unpack into tiples, returns a tuple of similar indices
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
  return [ list(row) for row in zip(*a)]

transpose_matrix(a)

[[1, 3, 5], [2, 4, 6]]

##Transformation Matrix from Basis B to C (easy) ✔
Given basis vectors in two different bases B and C for R^3, write a Python function to compute the transformation matrix P from basis B to C.


 #### To Change Basis:

1. **Compute the Transformation Matrix**:

   $$
   P = C^{-1} \times B
   $$

2. **Find the New Coordinates**:

   $$
   [\mathbf{v}]_C = P \times [\mathbf{v}]_B
   $$


In [22]:
B = [[1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]]
C = [[1, 2.3, 3],
    [4.4, 25, 6],
    [7.4, 8, 9]]


In [23]:
import numpy as np
def transform_basis(B: list[list[int]], C: list[list[int]]) -> list[list[float]]:

  #it's only for creating list so don't forget [],Doing it the hard way!
  C=np.array(C)
  C_inversed=np.linalg.inv(C)

  P_transposed = [[sum(c_row[col] * b_col[col] for col in range(len(c_row))) for c_row in C_inversed] for b_col in [list(row) for row in zip(*B)]]
  P=[list(row) for row in zip(*P_transposed)] #because the basis are the cols
  return np.round(P,4)

transform_basis(B,C)


array([[-0.6772, -0.0126,  0.2342],
       [-0.0184,  0.0505, -0.0275],
       [ 0.5732, -0.0345, -0.0569]])

In [24]:
import numpy as np
def transform_basis(B: list[list[int]], C: list[list[int]]) -> list[list[float]]:

  #it's only for creating list so don't forget [],Doing it the hard way!
  B=np.array(B)
  C=np.array(C)
  C_inversed=np.linalg.inv(C)

  P= C_inversed.dot(B)
  return np.round(P,4)


transform_basis(B,C)

array([[-0.6772, -0.0126,  0.2342],
       [-0.0184,  0.0505, -0.0275],
       [ 0.5732, -0.0345, -0.0569]])

##Reshape Matrix (easy) ✔
Write a Python function that reshapes a given matrix into a specified shape.

In [25]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
	#Write your code here and return a python list after reshaping by using numpy's tolist() method
	#Find a way o assert it can be reshaped
  numbers_count=sum(len(row) for row in a)
  required_count=new_shape[0]*new_shape[1]
  if numbers_count!=required_count:
    return "It can't be reshaped"
  reshaped_matrix= np.array(a).reshape(new_shape).tolist()
  return reshaped_matrix

In [26]:
#test reshape matrix
a=[[1,2],[3,4],[5,6]]
new_shape=(2,3)
reshape_matrix(a,new_shape)
#test when can't be reshaped
# new_shape=(3,3)
# reshape_matrix(a,new_shape)

[[1, 2, 3], [4, 5, 6]]

##Convert Vector to Diagonal Matrix(easy) ✔
Write a Python function to convert a 1D numpy array into a diagonal matrix. The function should take in a 1D numpy array x and return a 2D numpy array representing the diagonal matrix.

In [27]:
x = np.array([1, 2, 3])

In [28]:
import numpy as np
#Using for loop and zeros matrix
def make_diagonal(x):
	# Your code here
	length=len(x)
	output=np.zeros((length,length))
	for i in range(length):
		output[i][i]=x[i]
	return output

make_diagonal(x)

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [29]:
def make_diagonal(x):
  Identity=np.identity(len(x))
  output=Identity*x
  return output
make_diagonal(x)

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

##Calculate Mean by Row or Column (easy) ✔
Write a Python function that calculates the mean of a matrix either by row or by column, based on a given mode. The function should take a matrix (list of lists) and a mode ('row' or 'column') as input and return a list of means according to the specified mode.

In [30]:
def calculate_matrix_mean(matrix: list[list[float]], mode: str) -> list[float]:
	if mode == 'column':
		return [sum(col)/len(col) for col in zip(*matrix)]
	elif mode == "row":
		return [sum(row)/len(row) for row in matrix]
	else:
		return "You didn't specify a mode: row,column"

#test calculate_matrix_mean
matrix=[[1,2,3],[4,5,6]]
mode="column"
calculate_matrix_mean(matrix,mode)

[2.5, 3.5, 4.5]

##Scalar Multiplication of a Matrix (easy) ✔
Write a Python function that multiplies a matrix by a scalar and returns the result.

In [31]:
#Using list comprehension
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
	return [[element * scalar for element in row] for row in matrix]

#Test scalar_multiply
matrix=[[1,2,3],[4,5,6]]
scalar=2
scalar_multiply(matrix,scalar)

[[2, 4, 6], [8, 10, 12]]

In [32]:
#Using numpy and broadcasting
import numpy as np
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
	return (np.array(matrix)*scalar).tolist()
#test scalar_multiply
matrix=[[1,2,3],[4,5,6]]
scalar=2
scalar_multiply(matrix,scalar)


[[2, 4, 6], [8, 10, 12]]

#Linear Algebra Medium (11 problems)!

##next